server:
  port: 8888

//spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/projects/microservices/config-server/config-repo

spring:
  profiles:
    active: native
